### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by facchinm** [arduino-libraries/Arduino_Braccio_plusplus#1]
- [x] Implement multiple movements (`moveTo` complete API) https://github.com/bcmi-labs/Braccio_v2_library/blob/master/src/Braccio%2B%2B.h#L61
- [x] Implement position APIs wrappers
- [ ] Implement speed() APIs (with `chrono_literals`)
- [x] Rework `ping_allowed` to make it lock/unlock automatically
@Esquirio
